use Traning;
 
SELECT DNAME , LOC 
FROM DEPT;


SELECT ENAME , EMPNO
FROM EMP;

SELECT ENAME , SAL , COMM, JOB 
FROM EMP;

SELECT ENAME , SAL , SAL * 12 AS 'ANNUAL SALARY'
FROM EMP;

SELECT DISTINCT DEPTNO
FROM DEPT;

SELECT ENAME , SAL, SAL*12 AS ' ANNUAL SALARY' ,(SAL + (SAL* 0.2) )*12 AS 'ANNUAL SALARY AFTER HIKE'
FROM EMP;