SELECT ENAME , JOB
FROM EMP
WHERE JOB LIKE 'MANAGER';

SELECT EMPNO, JOB,
CASE
WHEN JOB !='SALESMAN' THEN 'NON SALES'
ELSE 'SALES'
END AS 'SALES V/S NON SALES'
FROM EMP;



SELECT EMPNO, SAL,
CASE
WHEN SAL >1000 THEN SAL
ELSE '1000'
END
FROM EMP;



SELECT EMPNO, SAL,
CASE
WHEN SAL < 1000 THEN 'LOW'
WHEN SAL > 1000 AND SAL <2500 THEN 'MEDIUM'
ELSE 'HIGH'
END
FROM EMP;

SELECT ENAME
FROM EMP
WHERE SAL < ANY (SELECT SAL
			FROM EMP
			WHERE ENAME LIKE 'miller')
AND  JOB LIKE 'salesman';

SELECT e.*
FROM EMP e , DEPT d
WHERE d.LOC LIKE 'CHICAGO';

SELECT ENAME
FROM EMP 
WHERE SAL > (SELECT MIN(SAL)
			FROM EMP
			WHERE JOB LIKE 'manager');

SELECT ENAME , EMPNO
FROM EMP 
WHERE EXISTS (SELECT 'X'
			  FROM DEPT
			  WHERE DNAME LIKE 'ACCOUNTING');

SELECT COUNT(ENAME)
FROM EMP e , DEPT d
WHERE (e.DEPTNO = d.DEPTNO) AND d.LOC LIKE 'CHICAGO';

SELECT ENAME
FROM EMP e , DEPT d
WHERE (e.DEPTNO = d.DEPTNO) AND d.LOC LIKE 'CHICAGO';

SELECT d.DNAME
FROM EMP e , DEPT d
WHERE (e.DEPTNO = d.DEPTNO) AND e.ENAME is NULL ;

SELECT ENAME , JOB
FROM EMP 
WHERE MGR is NULL;



SELECT EMP.ENAME, EMP.JOB 
FROM EMP, DEPT
WHERE EMP.DEPTNO = DEPT.DEPTNO AND LOC='NEW YORK' AND COMM>1000;

SELECT *
FROM EMP;

